"""Initial migration

Revision ID: 5e06b1f1c69d
Revises: 
Create Date: 2025-12-15 18:32:10.049003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e06b1f1c69d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service__history', schema=None) as batch_op:
        batch_op.drop_column('remarksname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service__history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarksname', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
